### ISSUE TITLE
the touch control for putting the wrong letter back is in the wrong place

### ISSUE THREAD

**Issue by m010388f** [JMozza/Team-Skyrim#4]
[BOUNDING BOX GLITCH AND TOUCH CONTROL GLITCH]
1. pick up the wrong, second letter.
2. try touching the letter to put it back into the game world.
3. the location to put the letter back is near the end of the screen.
4. this get worse when you get the third or fourth letter wrong.

when the player need to put the letter back into the game world, they will be unable to do so without pressing at random points on the screen. this means that the player may not be able to complete the game.

the bounding box for the touch should be on the incorrect letter it self.

bug rating - 4, major
game-play bug

**Comment by daniel-davenport004** [comment]
Fixed
